{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "from azureml.core import Workspace\n",
    "from dotenv import load_dotenv, find_dotenv\n",
    "_ = load_dotenv(find_dotenv())\n",
    "\n",
    "# Access the Workspace\n",
    "ws = Workspace.from_config(\"./config\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{\n",
       "    \"assetId\": \"azureml://locations/westus/workspaces/54b058d1-e724-4986-aece-5eb3256cb2e6/environments/MyEnvironmentAuto/versions/2\",\n",
       "    \"databricks\": {\n",
       "        \"eggLibraries\": [],\n",
       "        \"jarLibraries\": [],\n",
       "        \"mavenLibraries\": [],\n",
       "        \"pypiLibraries\": [],\n",
       "        \"rcranLibraries\": []\n",
       "    },\n",
       "    \"docker\": {\n",
       "        \"arguments\": [],\n",
       "        \"baseDockerfile\": null,\n",
       "        \"baseImage\": \"mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240304.v1\",\n",
       "        \"baseImageRegistry\": {\n",
       "            \"address\": null,\n",
       "            \"password\": null,\n",
       "            \"registryIdentity\": null,\n",
       "            \"username\": null\n",
       "        },\n",
       "        \"buildContext\": null,\n",
       "        \"enabled\": false,\n",
       "        \"platform\": {\n",
       "            \"architecture\": \"amd64\",\n",
       "            \"os\": \"Linux\"\n",
       "        },\n",
       "        \"sharedVolumes\": true,\n",
       "        \"shmSize\": null\n",
       "    },\n",
       "    \"environmentVariables\": {\n",
       "        \"EXAMPLE_ENV_VAR\": \"EXAMPLE_VALUE\"\n",
       "    },\n",
       "    \"inferencingStackVersion\": null,\n",
       "    \"name\": \"MyEnvironmentAuto\",\n",
       "    \"python\": {\n",
       "        \"baseCondaEnvironment\": null,\n",
       "        \"condaDependencies\": {\n",
       "            \"channels\": [\n",
       "                \"anaconda\",\n",
       "                \"conda-forge\"\n",
       "            ],\n",
       "            \"dependencies\": [\n",
       "                \"python=3.8.13\",\n",
       "                {\n",
       "                    \"pip\": [\n",
       "                        \"azureml-defaults\"\n",
       "                    ]\n",
       "                },\n",
       "                \"scikit-learn\",\n",
       "                \"pandas\"\n",
       "            ],\n",
       "            \"name\": \"project_environment\"\n",
       "        },\n",
       "        \"condaDependenciesFile\": null,\n",
       "        \"interpreterPath\": \"python\",\n",
       "        \"userManagedDependencies\": false\n",
       "    },\n",
       "    \"r\": null,\n",
       "    \"spark\": {\n",
       "        \"packages\": [],\n",
       "        \"precachePackages\": true,\n",
       "        \"repositories\": []\n",
       "    },\n",
       "    \"version\": \"2\"\n",
       "}"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Create custom environment\n",
    "from azureml.core import Environment\n",
    "from azureml.core.environment import CondaDependencies\n",
    "\n",
    "myenv = Environment(name=\"MyEnvironmentAuto\")\n",
    "myenv_dep = CondaDependencies.create(conda_packages=['scikit-learn', 'pandas'])\n",
    "myenv.python.conda_dependencies = myenv_dep\n",
    "myenv.register(ws)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Provisioning operation finished, operation \"Succeeded\"\n"
     ]
    }
   ],
   "source": [
    "# Create a compute cluster for pipeline\n",
    "\n",
    "cluster_name = \"pipeline-cluster\"\n",
    "\n",
    "from azureml.core.compute import AmlCompute, ComputeTarget\n",
    "compute_config = AmlCompute.provisioning_configuration(\n",
    "    vm_size=\"STANDARD_D11_V2\",\n",
    "    max_nodes=2\n",
    ")\n",
    "\n",
    "compute_cluster = ComputeTarget.create(ws, cluster_name, compute_config)\n",
    "compute_cluster.wait_for_completion()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Created step 01 Data Preparation [b7f8994f][afa1209e-7c29-41fb-8ff5-bbd27e8036d6], (This step will run and generate new outputs)\n",
      "Created step 02 Train the Model [556c447f][bec7298e-ca10-4989-b6f3-602f5771bc92], (This step will run and generate new outputs)\n",
      "Submitted PipelineRun 0935b6ed-10c5-42e3-936d-4eef8fa82e1f\n",
      "Link to Azure Machine Learning Portal: https://ml.azure.com/runs/0935b6ed-10c5-42e3-936d-4eef8fa82e1f?wsid=/subscriptions/49e690c2-0fc4-42a6-ba64-9ea0fa04ddda/resourcegroups/AzureMLsdkgroup/workspaces/slavasdkworkspace&tid=77487836-da45-4554-ad65-1775dca67ca5\n",
      "PipelineRunId: 0935b6ed-10c5-42e3-936d-4eef8fa82e1f\n",
      "Link to Azure Machine Learning Portal: https://ml.azure.com/runs/0935b6ed-10c5-42e3-936d-4eef8fa82e1f?wsid=/subscriptions/49e690c2-0fc4-42a6-ba64-9ea0fa04ddda/resourcegroups/AzureMLsdkgroup/workspaces/slavasdkworkspace&tid=77487836-da45-4554-ad65-1775dca67ca5\n",
      "PipelineRun Status: Running\n",
      "\n",
      "\n",
      "StepRunId: 99dcc163-3488-4096-9d34-b6501fb0e94d\n",
      "Link to Azure Machine Learning Portal: https://ml.azure.com/runs/99dcc163-3488-4096-9d34-b6501fb0e94d?wsid=/subscriptions/49e690c2-0fc4-42a6-ba64-9ea0fa04ddda/resourcegroups/AzureMLsdkgroup/workspaces/slavasdkworkspace&tid=77487836-da45-4554-ad65-1775dca67ca5\n",
      "StepRun( 01 Data Preparation ) Status: NotStarted\n",
      "\n",
      "Streaming azureml-logs/20_image_build_log.txt\n",
      "=============================================\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "StepRun( 01 Data Preparation ) Status: Running\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n",
      "Ran into a deserialization error. Ignoring since this is failsafe deserialization\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1509, in failsafe_deserialize\n",
      "    return self(target_obj, data, content_type=content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1375, in __call__\n",
      "    data = self._unpack_content(response_data, content_type)\n",
      "  File \"c:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\msrest\\serialization.py\", line 1543, in _unpack_content\n",
      "    raise ValueError(\"This pipeline didn't have the RawDeserializer policy; can't deserialize\")\n",
      "ValueError: This pipeline didn't have the RawDeserializer policy; can't deserialize\n"
     ]
    },
    {
     "ename": "ExperimentExecutionException",
     "evalue": "ExperimentExecutionException:\n\tMessage: The output streaming for the run interrupted.\nBut the run is still executing on the compute target. \nDetails for canceling the run can be found here: https://aka.ms/aml-docs-cancel-run\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"The output streaming for the run interrupted.\\nBut the run is still executing on the compute target. \\nDetails for canceling the run can be found here: https://aka.ms/aml-docs-cancel-run\"\n    }\n}",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\pipeline\\core\\run.py:742\u001b[0m, in \u001b[0;36mStepRun.wait_for_completion\u001b[1;34m(self, show_output, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[0;32m    741\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 742\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_stream_run_output\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout_seconds\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout_seconds\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    743\u001b[0m \u001b[43m                                   \u001b[49m\u001b[43mraise_on_error\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mraise_on_error\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    744\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyboardInterrupt\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\pipeline\\core\\run.py:804\u001b[0m, in \u001b[0;36mStepRun._stream_run_output\u001b[1;34m(self, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[0;32m    803\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 804\u001b[0m     content \u001b[38;5;241m=\u001b[39m \u001b[43mdownload_file_stream\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcurrent_log_uri\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43msession\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msession\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    805\u001b[0m     num_printed_lines \u001b[38;5;241m=\u001b[39m incremental_print(content, num_printed_lines)\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_file_utils\\file_utils.py:316\u001b[0m, in \u001b[0;36mdownload_file_stream\u001b[1;34m(source_uri, encoding, download_to_bytes, max_retries, stream, protocol, session, _validate_check_sum, max_concurrency)\u001b[0m\n\u001b[0;32m    314\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m blob\u001b[38;5;241m.\u001b[39mreadall()\n\u001b[1;32m--> 316\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43m_retry\u001b[49m\u001b[43m(\u001b[49m\u001b[43mexec_func\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmax_retries\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmax_retries\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    318\u001b[0m \u001b[38;5;66;03m# download using requests.Session\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_file_utils\\file_utils.py:468\u001b[0m, in \u001b[0;36m_retry\u001b[1;34m(exec_func, clean_up_func, max_retries, retry_on_exceptions, fail_on_exceptions)\u001b[0m\n\u001b[0;32m    467\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 468\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mexec_func\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    469\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m fail_on_exceptions \u001b[38;5;28;01mas\u001b[39;00m ex:\n\u001b[0;32m    470\u001b[0m     \u001b[38;5;66;03m# if condition to fail on different exceptions differently\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_file_utils\\file_utils.py:306\u001b[0m, in \u001b[0;36mdownload_file_stream.<locals>.exec_func\u001b[1;34m()\u001b[0m\n\u001b[0;32m    305\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m--> 306\u001b[0m     blob \u001b[38;5;241m=\u001b[39m \u001b[43mblob_service\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_blob_client\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    307\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcontainer\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mcontainer_name\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    308\u001b[0m \u001b[43m        \u001b[49m\u001b[43mblob\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mblob_name\u001b[49m\n\u001b[0;32m    309\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mdownload_blob\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    310\u001b[0m \u001b[43m        \u001b[49m\u001b[43mmax_concurrency\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmax_concurrency\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    311\u001b[0m \u001b[43m        \u001b[49m\u001b[43mvalidate_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m_validate_check_sum\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    312\u001b[0m \u001b[43m        \u001b[49m\u001b[43mencoding\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mencoding\u001b[49m\n\u001b[0;32m    313\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    314\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m blob\u001b[38;5;241m.\u001b[39mreadall()\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\tracing\\decorator.py:78\u001b[0m, in \u001b[0;36mdistributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     77\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m span_impl_type \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m---> 78\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m     80\u001b[0m \u001b[38;5;66;03m# Merge span is parameter is set, but only if no explicit parent are passed\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_vendor\\azure_storage\\blob\\_blob_client.py:871\u001b[0m, in \u001b[0;36mBlobClient.download_blob\u001b[1;34m(self, offset, length, **kwargs)\u001b[0m\n\u001b[0;32m    867\u001b[0m options \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_download_blob_options(\n\u001b[0;32m    868\u001b[0m     offset\u001b[38;5;241m=\u001b[39moffset,\n\u001b[0;32m    869\u001b[0m     length\u001b[38;5;241m=\u001b[39mlength,\n\u001b[0;32m    870\u001b[0m     \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[1;32m--> 871\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m StorageStreamDownloader(\u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39moptions)\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_vendor\\azure_storage\\blob\\_download.py:359\u001b[0m, in \u001b[0;36mStorageStreamDownloader.__init__\u001b[1;34m(self, clients, config, start_range, end_range, validate_content, encryption_options, max_concurrency, name, container, encoding, **kwargs)\u001b[0m\n\u001b[0;32m    351\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_initial_range, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_initial_offset \u001b[38;5;241m=\u001b[39m process_range_and_offset(\n\u001b[0;32m    352\u001b[0m     initial_request_start,\n\u001b[0;32m    353\u001b[0m     initial_request_end,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    356\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_encryption_data\n\u001b[0;32m    357\u001b[0m )\n\u001b[1;32m--> 359\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_initial_request\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    360\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mproperties \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_response\u001b[38;5;241m.\u001b[39mproperties\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_vendor\\azure_storage\\blob\\_download.py:411\u001b[0m, in \u001b[0;36mStorageStreamDownloader._initial_request\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    410\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 411\u001b[0m     location_mode, response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_clients\u001b[38;5;241m.\u001b[39mblob\u001b[38;5;241m.\u001b[39mdownload(\n\u001b[0;32m    412\u001b[0m         \u001b[38;5;28mrange\u001b[39m\u001b[38;5;241m=\u001b[39mrange_header,\n\u001b[0;32m    413\u001b[0m         range_get_content_md5\u001b[38;5;241m=\u001b[39mrange_validation,\n\u001b[0;32m    414\u001b[0m         validate_content\u001b[38;5;241m=\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_validate_content,\n\u001b[0;32m    415\u001b[0m         data_stream_total\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m,\n\u001b[0;32m    416\u001b[0m         download_stream_current\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m,\n\u001b[0;32m    417\u001b[0m         \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_request_options\n\u001b[0;32m    418\u001b[0m     )\n\u001b[0;32m    420\u001b[0m     \u001b[38;5;66;03m# Check the location we read from to ensure we use the same one\u001b[39;00m\n\u001b[0;32m    421\u001b[0m     \u001b[38;5;66;03m# for subsequent requests.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\tracing\\decorator.py:78\u001b[0m, in \u001b[0;36mdistributed_trace.<locals>.decorator.<locals>.wrapper_use_tracer\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     77\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m span_impl_type \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m---> 78\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m func(\u001b[38;5;241m*\u001b[39margs, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m     80\u001b[0m \u001b[38;5;66;03m# Merge span is parameter is set, but only if no explicit parent are passed\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_vendor\\azure_storage\\blob\\_generated\\operations\\_blob_operations.py:1700\u001b[0m, in \u001b[0;36mBlobOperations.download\u001b[1;34m(self, snapshot, version_id, timeout, range, range_get_content_md5, range_get_content_crc64, request_id_parameter, lease_access_conditions, cpk_info, modified_access_conditions, **kwargs)\u001b[0m\n\u001b[0;32m   1698\u001b[0m request\u001b[38;5;241m.\u001b[39murl \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_client\u001b[38;5;241m.\u001b[39mformat_url(request\u001b[38;5;241m.\u001b[39murl)  \u001b[38;5;66;03m# type: ignore\u001b[39;00m\n\u001b[1;32m-> 1700\u001b[0m pipeline_response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_client\u001b[38;5;241m.\u001b[39m_pipeline\u001b[38;5;241m.\u001b[39mrun(  \u001b[38;5;66;03m# type: ignore # pylint: disable=protected-access\u001b[39;00m\n\u001b[0;32m   1701\u001b[0m     request,\n\u001b[0;32m   1702\u001b[0m     stream\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m,\n\u001b[0;32m   1703\u001b[0m     \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs\n\u001b[0;32m   1704\u001b[0m )\n\u001b[0;32m   1705\u001b[0m response \u001b[38;5;241m=\u001b[39m pipeline_response\u001b[38;5;241m.\u001b[39mhttp_response\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:230\u001b[0m, in \u001b[0;36mPipeline.run\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    229\u001b[0m first_node \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_impl_policies[\u001b[38;5;241m0\u001b[39m] \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_impl_policies \u001b[38;5;28;01melse\u001b[39;00m _TransportRunner(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_transport)\n\u001b[1;32m--> 230\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfirst_node\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mpipeline_request\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "    \u001b[1;31m[... skipping similar frames: _SansIOHTTPPolicyRunner.send at line 86 (2 times)]\u001b[0m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\policies\\_redirect.py:197\u001b[0m, in \u001b[0;36mRedirectPolicy.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m    196\u001b[0m \u001b[38;5;28;01mwhile\u001b[39;00m retryable:\n\u001b[1;32m--> 197\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    198\u001b[0m     redirect_location \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mget_redirect_location(response)\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_vendor\\azure_storage\\blob\\_shared\\policies.py:518\u001b[0m, in \u001b[0;36mStorageRetryPolicy.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m    517\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 518\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    519\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m is_retry(response, retry_settings[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mmode\u001b[39m\u001b[38;5;124m'\u001b[39m]):\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_vendor\\azure_storage\\blob\\_shared\\policies.py:313\u001b[0m, in \u001b[0;36mStorageResponseHook.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m    310\u001b[0m response_callback \u001b[38;5;241m=\u001b[39m request\u001b[38;5;241m.\u001b[39mcontext\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mresponse_callback\u001b[39m\u001b[38;5;124m'\u001b[39m) \u001b[38;5;129;01mor\u001b[39;00m \\\n\u001b[0;32m    311\u001b[0m     request\u001b[38;5;241m.\u001b[39mcontext\u001b[38;5;241m.\u001b[39moptions\u001b[38;5;241m.\u001b[39mpop(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mraw_response_hook\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_response_callback)\n\u001b[1;32m--> 313\u001b[0m response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    315\u001b[0m will_retry \u001b[38;5;241m=\u001b[39m is_retry(response, request\u001b[38;5;241m.\u001b[39mcontext\u001b[38;5;241m.\u001b[39moptions\u001b[38;5;241m.\u001b[39mget(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mmode\u001b[39m\u001b[38;5;124m'\u001b[39m))\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:86\u001b[0m, in \u001b[0;36m_SansIOHTTPPolicyRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m     85\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m---> 86\u001b[0m     response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mnext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msend\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     87\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\_base.py:119\u001b[0m, in \u001b[0;36m_TransportRunner.send\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m    116\u001b[0m cleanup_kwargs_for_transport(request\u001b[38;5;241m.\u001b[39mcontext\u001b[38;5;241m.\u001b[39moptions)\n\u001b[0;32m    117\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m PipelineResponse(\n\u001b[0;32m    118\u001b[0m     request\u001b[38;5;241m.\u001b[39mhttp_request,\n\u001b[1;32m--> 119\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_sender\u001b[38;5;241m.\u001b[39msend(request\u001b[38;5;241m.\u001b[39mhttp_request, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mrequest\u001b[38;5;241m.\u001b[39mcontext\u001b[38;5;241m.\u001b[39moptions),\n\u001b[0;32m    120\u001b[0m     context\u001b[38;5;241m=\u001b[39mrequest\u001b[38;5;241m.\u001b[39mcontext,\n\u001b[0;32m    121\u001b[0m )\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\_vendor\\azure_storage\\blob\\_shared\\base_client.py:330\u001b[0m, in \u001b[0;36mTransportWrapper.send\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    329\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21msend\u001b[39m(\u001b[38;5;28mself\u001b[39m, request, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs):\n\u001b[1;32m--> 330\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_transport\u001b[38;5;241m.\u001b[39msend(request, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azure\\core\\pipeline\\transport\\_requests_basic.py:347\u001b[0m, in \u001b[0;36mRequestsTransport.send\u001b[1;34m(self, request, proxies, **kwargs)\u001b[0m\n\u001b[0;32m    346\u001b[0m     timeout \u001b[38;5;241m=\u001b[39m (connection_timeout, read_timeout)\n\u001b[1;32m--> 347\u001b[0m response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msession\u001b[38;5;241m.\u001b[39mrequest(  \u001b[38;5;66;03m# type: ignore\u001b[39;00m\n\u001b[0;32m    348\u001b[0m     request\u001b[38;5;241m.\u001b[39mmethod,\n\u001b[0;32m    349\u001b[0m     request\u001b[38;5;241m.\u001b[39murl,\n\u001b[0;32m    350\u001b[0m     headers\u001b[38;5;241m=\u001b[39mrequest\u001b[38;5;241m.\u001b[39mheaders,\n\u001b[0;32m    351\u001b[0m     data\u001b[38;5;241m=\u001b[39mrequest\u001b[38;5;241m.\u001b[39mdata,\n\u001b[0;32m    352\u001b[0m     files\u001b[38;5;241m=\u001b[39mrequest\u001b[38;5;241m.\u001b[39mfiles,\n\u001b[0;32m    353\u001b[0m     verify\u001b[38;5;241m=\u001b[39mkwargs\u001b[38;5;241m.\u001b[39mpop(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mconnection_verify\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mconnection_config\u001b[38;5;241m.\u001b[39mverify),\n\u001b[0;32m    354\u001b[0m     timeout\u001b[38;5;241m=\u001b[39mtimeout,\n\u001b[0;32m    355\u001b[0m     cert\u001b[38;5;241m=\u001b[39mkwargs\u001b[38;5;241m.\u001b[39mpop(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mconnection_cert\u001b[39m\u001b[38;5;124m\"\u001b[39m, \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mconnection_config\u001b[38;5;241m.\u001b[39mcert),\n\u001b[0;32m    356\u001b[0m     allow_redirects\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m,\n\u001b[0;32m    357\u001b[0m     proxies\u001b[38;5;241m=\u001b[39mproxies,\n\u001b[0;32m    358\u001b[0m     \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs\n\u001b[0;32m    359\u001b[0m )\n\u001b[0;32m    360\u001b[0m response\u001b[38;5;241m.\u001b[39mraw\u001b[38;5;241m.\u001b[39menforce_content_length \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mTrue\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\requests\\sessions.py:589\u001b[0m, in \u001b[0;36mSession.request\u001b[1;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[0;32m    588\u001b[0m send_kwargs\u001b[38;5;241m.\u001b[39mupdate(settings)\n\u001b[1;32m--> 589\u001b[0m resp \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msend(prep, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39msend_kwargs)\n\u001b[0;32m    591\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m resp\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\requests\\sessions.py:703\u001b[0m, in \u001b[0;36mSession.send\u001b[1;34m(self, request, **kwargs)\u001b[0m\n\u001b[0;32m    702\u001b[0m \u001b[38;5;66;03m# Send the request\u001b[39;00m\n\u001b[1;32m--> 703\u001b[0m r \u001b[38;5;241m=\u001b[39m adapter\u001b[38;5;241m.\u001b[39msend(request, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkwargs)\n\u001b[0;32m    705\u001b[0m \u001b[38;5;66;03m# Total elapsed time of the request (approximately)\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\requests\\adapters.py:486\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[1;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[0;32m    485\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 486\u001b[0m     resp \u001b[38;5;241m=\u001b[39m \u001b[43mconn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43murlopen\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    487\u001b[0m \u001b[43m        \u001b[49m\u001b[43mmethod\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmethod\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    488\u001b[0m \u001b[43m        \u001b[49m\u001b[43murl\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43murl\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    489\u001b[0m \u001b[43m        \u001b[49m\u001b[43mbody\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mbody\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    490\u001b[0m \u001b[43m        \u001b[49m\u001b[43mheaders\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mheaders\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    491\u001b[0m \u001b[43m        \u001b[49m\u001b[43mredirect\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    492\u001b[0m \u001b[43m        \u001b[49m\u001b[43massert_same_host\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    493\u001b[0m \u001b[43m        \u001b[49m\u001b[43mpreload_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    494\u001b[0m \u001b[43m        \u001b[49m\u001b[43mdecode_content\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    495\u001b[0m \u001b[43m        \u001b[49m\u001b[43mretries\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmax_retries\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    496\u001b[0m \u001b[43m        \u001b[49m\u001b[43mtimeout\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    497\u001b[0m \u001b[43m        \u001b[49m\u001b[43mchunked\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mchunked\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    498\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    500\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (ProtocolError, \u001b[38;5;167;01mOSError\u001b[39;00m) \u001b[38;5;28;01mas\u001b[39;00m err:\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\urllib3\\connectionpool.py:793\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[1;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)\u001b[0m\n\u001b[0;32m    792\u001b[0m \u001b[38;5;66;03m# Make the request on the HTTPConnection object\u001b[39;00m\n\u001b[1;32m--> 793\u001b[0m response \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_make_request(\n\u001b[0;32m    794\u001b[0m     conn,\n\u001b[0;32m    795\u001b[0m     method,\n\u001b[0;32m    796\u001b[0m     url,\n\u001b[0;32m    797\u001b[0m     timeout\u001b[38;5;241m=\u001b[39mtimeout_obj,\n\u001b[0;32m    798\u001b[0m     body\u001b[38;5;241m=\u001b[39mbody,\n\u001b[0;32m    799\u001b[0m     headers\u001b[38;5;241m=\u001b[39mheaders,\n\u001b[0;32m    800\u001b[0m     chunked\u001b[38;5;241m=\u001b[39mchunked,\n\u001b[0;32m    801\u001b[0m     retries\u001b[38;5;241m=\u001b[39mretries,\n\u001b[0;32m    802\u001b[0m     response_conn\u001b[38;5;241m=\u001b[39mresponse_conn,\n\u001b[0;32m    803\u001b[0m     preload_content\u001b[38;5;241m=\u001b[39mpreload_content,\n\u001b[0;32m    804\u001b[0m     decode_content\u001b[38;5;241m=\u001b[39mdecode_content,\n\u001b[0;32m    805\u001b[0m     \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mresponse_kw,\n\u001b[0;32m    806\u001b[0m )\n\u001b[0;32m    808\u001b[0m \u001b[38;5;66;03m# Everything went great!\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\urllib3\\connectionpool.py:467\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[1;34m(self, conn, method, url, body, headers, retries, timeout, chunked, response_conn, preload_content, decode_content, enforce_content_length)\u001b[0m\n\u001b[0;32m    466\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 467\u001b[0m     \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_validate_conn\u001b[49m\u001b[43m(\u001b[49m\u001b[43mconn\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    468\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m (SocketTimeout, BaseSSLError) \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\urllib3\\connectionpool.py:1099\u001b[0m, in \u001b[0;36mHTTPSConnectionPool._validate_conn\u001b[1;34m(self, conn)\u001b[0m\n\u001b[0;32m   1098\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m conn\u001b[38;5;241m.\u001b[39mis_closed:\n\u001b[1;32m-> 1099\u001b[0m     \u001b[43mconn\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m   1101\u001b[0m \u001b[38;5;66;03m# TODO revise this, see https://github.com/urllib3/urllib3/issues/2791\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\urllib3\\connection.py:616\u001b[0m, in \u001b[0;36mHTTPSConnection.connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    615\u001b[0m sock: socket\u001b[38;5;241m.\u001b[39msocket \u001b[38;5;241m|\u001b[39m ssl\u001b[38;5;241m.\u001b[39mSSLSocket\n\u001b[1;32m--> 616\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msock \u001b[38;5;241m=\u001b[39m sock \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_new_conn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    617\u001b[0m server_hostname: \u001b[38;5;28mstr\u001b[39m \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mhost\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\urllib3\\connection.py:198\u001b[0m, in \u001b[0;36mHTTPConnection._new_conn\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    197\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 198\u001b[0m     sock \u001b[38;5;241m=\u001b[39m \u001b[43mconnection\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcreate_connection\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m    199\u001b[0m \u001b[43m        \u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_dns_host\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mport\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    200\u001b[0m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtimeout\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    201\u001b[0m \u001b[43m        \u001b[49m\u001b[43msource_address\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msource_address\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    202\u001b[0m \u001b[43m        \u001b[49m\u001b[43msocket_options\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43msocket_options\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    203\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    204\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m socket\u001b[38;5;241m.\u001b[39mgaierror \u001b[38;5;28;01mas\u001b[39;00m e:\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\urllib3\\util\\connection.py:73\u001b[0m, in \u001b[0;36mcreate_connection\u001b[1;34m(address, timeout, source_address, socket_options)\u001b[0m\n\u001b[0;32m     72\u001b[0m     sock\u001b[38;5;241m.\u001b[39mbind(source_address)\n\u001b[1;32m---> 73\u001b[0m \u001b[43msock\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnect\u001b[49m\u001b[43m(\u001b[49m\u001b[43msa\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     74\u001b[0m \u001b[38;5;66;03m# Break explicitly a reference cycle\u001b[39;00m\n",
      "\u001b[1;31mKeyboardInterrupt\u001b[0m: ",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mExperimentExecutionException\u001b[0m              Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[8], line 44\u001b[0m\n\u001b[0;32m     42\u001b[0m new_experiment \u001b[38;5;241m=\u001b[39m Experiment(workspace\u001b[38;5;241m=\u001b[39mws, name\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPipelineExp01\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[0;32m     43\u001b[0m new_pipeline_run \u001b[38;5;241m=\u001b[39m new_experiment\u001b[38;5;241m.\u001b[39msubmit(new_pipeline)\n\u001b[1;32m---> 44\u001b[0m \u001b[43mnew_pipeline_run\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait_for_completion\u001b[49m\u001b[43m(\u001b[49m\u001b[43mshow_output\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\pipeline\\core\\run.py:295\u001b[0m, in \u001b[0;36mPipelineRun.wait_for_completion\u001b[1;34m(self, show_output, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[0;32m    293\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m'\u001b[39m)\n\u001b[0;32m    294\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m--> 295\u001b[0m     \u001b[43mstep_run\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait_for_completion\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout_seconds\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout_seconds\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m-\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mtime_elapsed\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m    296\u001b[0m \u001b[43m                                 \u001b[49m\u001b[43mraise_on_error\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mraise_on_error\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    297\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m    298\u001b[0m     \u001b[38;5;66;03m# If there are package conflicts in the user's environment, the run rehydration\u001b[39;00m\n\u001b[0;32m    299\u001b[0m     \u001b[38;5;66;03m# will not work and we will receive a Run object instead of StepRun.\u001b[39;00m\n\u001b[0;32m    300\u001b[0m     \u001b[38;5;66;03m# Run.wait_for_completion() does not have a parameter timeout_seconds, which\u001b[39;00m\n\u001b[0;32m    301\u001b[0m     \u001b[38;5;66;03m# will generate a TypeError here.  As a workaround, call the method without\u001b[39;00m\n\u001b[0;32m    302\u001b[0m     \u001b[38;5;66;03m# this parameter.\u001b[39;00m\n\u001b[0;32m    303\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(step_run, StepRun):\n",
      "File \u001b[1;32mc:\\Users\\User\\anaconda3\\envs\\newtensorflow\\lib\\site-packages\\azureml\\pipeline\\core\\run.py:750\u001b[0m, in \u001b[0;36mStepRun.wait_for_completion\u001b[1;34m(self, show_output, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[0;32m    744\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyboardInterrupt\u001b[39;00m:\n\u001b[0;32m    745\u001b[0m         error_message \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe output streaming for the run interrupted.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \\\n\u001b[0;32m    746\u001b[0m                         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBut the run is still executing on the compute target. \u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \\\n\u001b[0;32m    747\u001b[0m                         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mDetails for canceling the run can be found here: \u001b[39m\u001b[38;5;124m\"\u001b[39m \\\n\u001b[0;32m    748\u001b[0m                         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhttps://aka.ms/aml-docs-cancel-run\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m--> 750\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m ExperimentExecutionException(error_message)\n\u001b[0;32m    751\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m    752\u001b[0m     status \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mget_status()\n",
      "\u001b[1;31mExperimentExecutionException\u001b[0m: ExperimentExecutionException:\n\tMessage: The output streaming for the run interrupted.\nBut the run is still executing on the compute target. \nDetails for canceling the run can be found here: https://aka.ms/aml-docs-cancel-run\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"The output streaming for the run interrupted.\\nBut the run is still executing on the compute target. \\nDetails for canceling the run can be found here: https://aka.ms/aml-docs-cancel-run\"\n    }\n}"
     ]
    }
   ],
   "source": [
    "# Define Pipeline steps\n",
    "\n",
    "# Create Run Configurations for the steps\n",
    "from azureml.core.runconfig import RunConfiguration\n",
    "run_config = RunConfiguration()\n",
    "run_config.target = compute_cluster\n",
    "run_config.environment = myenv\n",
    "\n",
    "# Define inputs and outputs\n",
    "from azureml.pipeline.steps import PythonScriptStep\n",
    "from azureml.pipeline.core import PipelineData\n",
    "input_ds = ws.datasets.get(\"Defaults\")\n",
    "dataFolder = PipelineData(\"datafolder\", datastore=ws.get_default_datastore())\n",
    "\n",
    "\n",
    "# Step 01 - Data Preparation\n",
    "dataPrep_step = PythonScriptStep(name=\"01 Data Preparation\",\n",
    "                                 source_directory=\".\",\n",
    "                                 script_name=\"220 - Dataprep Pipeline.py\",\n",
    "                                 inputs=[input_ds.as_named_input(\"raw_data\")],\n",
    "                                 outputs=[dataFolder],\n",
    "                                 runconfig=run_config,\n",
    "                                 arguments=[\"--datafolder\", dataFolder])\n",
    "\n",
    "# Step 02 - Train the model\n",
    "train_step = PythonScriptStep(name=\"02 Train the Model\",\n",
    "                                 source_directory=\".\",\n",
    "                                 script_name=\"220 - Training Pipeline.py\",\n",
    "                                 inputs=[dataFolder],\n",
    "                                 runconfig=run_config,\n",
    "                                 arguments=[\"--datafolder\", dataFolder])\n",
    "\n",
    "# Configure and build the pipeline\n",
    "from azureml.pipeline.core import Pipeline\n",
    "steps = [dataPrep_step, train_step]\n",
    "new_pipeline = Pipeline(workspace=ws, steps=steps)\n",
    "\n",
    "\n",
    "# Create the experiment and run the pipeline\n",
    "from azureml.core import Experiment\n",
    "\n",
    "new_experiment = Experiment(workspace=ws, name=\"PipelineExp01\")\n",
    "new_pipeline_run = new_experiment.submit(new_pipeline)\n",
    "new_pipeline_run.wait_for_completion(show_output=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "newtensorflow",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
